---
## taint control plane nodes to not run any payload application
kubernetes_dedicated_control_plane: true

kubernetes_api_cert_sans_extra: []
kubernetes_network_dns_domain: cluster.local
# kubernetes_kubeadm_kubelet_extra_config:
#   resolvConf: /etc/resolv-upstreamonly.conf
kubernetes_controller_manager_bind_address: 0.0.0.0
kubernetes_scheduler_bind_address: 0.0.0.0
