---
apt_repo_ubuntu_nginx_repo_base_url: https://ppa.launchpadcontent.net/ondrej/nginx/
apt_repo_ubuntu_nginx_repo_gpg_key: |
  -----BEGIN PGP PUBLIC KEY BLOCK-----
  Comment: Hostname:
  Version: Hockeypuck 2.1.1-10-gec3b0e7

  xo0ESX35nAEEALKDCUDVXvmW9n+T/+3G1DnTpoWh9/1xNaz/RrUH6fQKhHr568F8
  hfnZP/2CGYVYkW9hxP9LVW9IDvzcmnhgIwK+ddeaPZqh3T/FM4OTA7Q78HSvR81m
  Jpf2iMLm/Zvh89ZsmP2sIgZuARiaHo8lxoTSLtmKXsM3FsJVlusyewHfABEBAAHN
  H0xhdW5jaHBhZCBQUEEgZm9yIE9uZMWZZWogU3Vyw73CtgQTAQIAIAUCSX35nAIb
  AwYLCQgHAwIEFQIIAwQWAgMBAh4BAheAAAoJEE9OoKrlJnpsQjYD/jW1NlIFAlT6
  EvF2xfVbkhERii9MapjaUsSso4XLCEmZdEGX54GQ01svXnrivwnd/kmhKvyxCqiN
  LDY/dOaK8MK//bDI6mqdKmG8XbP2vsdsxhifNC+GH/OwaDPvn1TyYB653kwyruCG
  FjEnCreZTcRUu2oBQyolORDl+BmF4DjL
  =LLQh
  -----END PGP PUBLIC KEY BLOCK-----
