---
extends: default

# This is the yamllint config used in ansible-lint: https://github.com/ansible/ansible-lint/blob/main/src/ansiblelint/yaml_utils.py
rules:
  comments:
    # https://github.com/prettier/prettier/issues/6780
    min-spaces-from-content: 1
  # https://github.com/adrienverge/yamllint/issues/384
  comments-indentation: false
  document-start: disable
  # 160 chars was the default used by old E204 rule, but
  # you can easily change it or disable in your .yamllint file.
  # ### disabled by us below:
  # line-length:
  #   max: 160
  # ###
  # We are adding an extra space inside braces as that's how prettier does it
  # and we are trying not to fight other linters.
  braces:
    min-spaces-inside: 0 # yamllint defaults to 0
    max-spaces-inside: 1 # yamllint defaults to 0
  ###
  # Additional rules by us:
  line-length: disable # TODO: enable with max: 160
