---
# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: mgit_at
name: roles
version: 0.1.0
readme: README.md
authors:
  - Markus Teufelberger (github.com/MarkusTeufelberger)
description: This collection contains common roles in active use by mgIT GmbH
license_file: LICENSE
tags:
# tags so people can search for collections https://galaxy.ansible.com/search
# tags are all lower-case, no spaces, no dashes.
  - openssh
  - kubernetes
repository: https://github.com/mgit-at/ansible-collection-roles
# documentation: https://github.com/mgit-at/ansible-collection-roles/tree/main/docs
homepage: https://github.com/mgit-at/ansible-collection-roles
issues: https://github.com/mgit-at/ansible-collection-roles/issues
build_ignore:
# https://docs.ansible.com/ansible/devel/dev_guide/developing_collections.html#ignoring-files-and-folders
  - .gitignore
  - changelogs/.plugin-cache.yaml
dependencies:
  # authorized_key
  "ansible.posix": ">=1.1.1"
  # ini_file
  "community.general": ">=2.0.1"
  # for the helm modules installing Cilium
  "kubernetes.core": ">=1.1.1"
