---
# Lists of versions used upstream:
# https://github.com/ansible-community/ansible-build-data

# This current set of versions corresponds to:
# Ansible 3.0.0

# This file just exists for ansible-lint, real dependencies are in galaxy.yml

collections:
  - name: ansible.posix
    version: 1.1.1
    source: https://galaxy.ansible.com
  - name: community.general
    version: 2.0.1
    source: https://galaxy.ansible.com
  - name: kubernetes.core
    version: 1.1.1
    source: https://galaxy.ansible.com
