---
# Lists of versions used upstream:
# https://github.com/ansible-community/ansible-build-data

# This current set of versions corresponds to:
# Ansible 6.7.0

# This file just exists for ansible-lint, real dependencies are in galaxy.yml

collections:
  - name: ansible.posix
    version: 1.4.0
    source: https://galaxy.ansible.com
  - name: community.general
    version: 5.8.3
    source: https://galaxy.ansible.com
  - name: kubernetes.core
    version: 2.3.2
    source: https://galaxy.ansible.com
