---
#### kubeadm wants token to come from --config if --config is used
#### i think this is stupid -> TODO: send bug report
# - name: generate bootstrap token for new cluster
#   ansible.builtin.command: kubeadm token generate
#   changed_when: False
#   check_mode: no
#   register: kubeadm_token_generate

- name: Initialize the kubernetes control plane without CNI and store log
  block:
    - name: Initialize the kubernetes initial control plane node
      ansible.builtin.command: |
        kubeadm
        init
        --config /etc/kubernetes/kubeadm.config
        --skip-token-print
      args:
        creates: /etc/kubernetes/pki/ca.crt
      register: kubeadm_init

  always:
    - name: Display output of kubeadm init
      when: kubeadm_init.changed
      ansible.builtin.debug:
        msg: "{{ kubeadm_init.stdout }}\n"

    - name: Display error output of kubeadm init
      when: kubeadm_init.changed and kubeadm_init.stderr
      ansible.builtin.debug:
        msg: "{{ kubeadm_init.stderr }}\n"

    - name: Dump output of kubeadm init to log file
      when: kubeadm_init.changed
      ansible.builtin.copy:
        content: "{{ kubeadm_init.stdout }}\n"
        dest: /etc/kubernetes/kubeadm-init.log

    - name: Dump error output of kubeadm init to log file
      when: kubeadm_init.changed and kubeadm_init.stderr
      ansible.builtin.copy:
        content: "{{ kubeadm_init.stderr }}\n"
        dest: /etc/kubernetes/kubeadm-init.errors

- name: Create a bootstrap token for this new cluster
  ansible.builtin.command: kubeadm token create --ttl 42m
  check_mode: false
  register: kubeadm_token_generate
  no_log: true
  changed_when: false  # this doesn't change cluster state

- name: Install Cilium
  ansible.builtin.include_tasks: net_cilium.yml

- name: Fetch list of current nodes in cluster
  ansible.builtin.command: kubectl get nodes -o name
  changed_when: false
  check_mode: false
  register: kubectl_node_list

- name: Save list of current nodes
  ansible.builtin.set_fact:
    kubernetes_current_nodes: "{{ kubectl_node_list.stdout_lines | map('replace', 'node/', '') | list }}"

- name: Upload certs
  when: "groups[kubernetes_control_plane_nodes_group_name] | map('extract', hostvars) | map(attribute='ansible_nodename') | difference(kubernetes_current_nodes) | length > 0"
  # noqa no-changed-when - yes, this is not idempotent
  # TODO: Get rid of the group name in there as well as in other tasks like this, this should be possible to infer otherwise
  ansible.builtin.command: kubeadm init phase upload-certs --upload-certs
  check_mode: false
  register: kubeadm_upload_certs
  no_log: true
