---
# This is necessary because to generate htpasswd within ansible
- name: Install required packages
  ansible.builtin.apt:
    name:
      - python3-passlib
    state: present

# This is necessary because the maintainers at Canonical
# dropped support for the lua module. See:
# https://launchpad.net/ubuntu/+source/nginx/1.24.0-1ubuntu1
# Currently this is just a problem for ubuntu starting from 22.04
# This is not really beautiful, but it won't let you install a
# broken nginx-extras without lua. As it won't technically be an
# error to have nginx-extras without lua
- name: Check for Ubuntu 22.04 or higher
  when:
    - nginx_base_pkg_variant == "nginx-extras"
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_major_version | int >= 22
  ansible.builtin.set_fact:
    nginx_base_ondrej_repo: true

- name: Install ondrej nginx repo
  when:
    - nginx_base_ondrej_repo
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_major_version | int >= 20
  ansible.builtin.include_role:
    name: mgit_at.roles.apt_repo_ubuntu_nginx

# The latest state will ensure that the nginx is installed from ondrej repository,
# when the repo is activated after the installation of the nginx package
- name: Install nginx
  ansible.builtin.apt:
    name: "{{ nginx_base_pkg_variant }}"
    state: "{% if nginx_base_ondrej_repo %}latest{% else %}present{% endif %}"
  notify: Restart nginx

- name: Create folder for http auth files
  ansible.builtin.file:
    path: /etc/nginx/auth
    state: directory
    owner: root
    group: www-data
    mode: "0750"

- name: Ensure nginx is always restarted
  loop:
    - [Service, Restart, always]
    - [Service, RestartSec, "1"]
    - [Unit, StartLimitIntervalSec, "0"]
  community.general.ini_file:
    path: /etc/systemd/system/nginx.service.d/override.conf
    owner: root
    group: root
    mode: "0644"
    section: "{{ item[0] }}"
    option: "{{ item[1] }}"
    value: "{{ item[2] }}"
    no_extra_spaces: true
  notify: Restart nginx

- name: Remove nginx default site
  ansible.builtin.file:
    name: /etc/nginx/sites-enabled/default
    state: absent
  notify: Restart nginx

- name: Install nginx config.d files
  when: nginx_base_conf_d_files | length > 0
  loop: "{{ nginx_base_conf_d_files }}"
  ansible.builtin.copy:
    src: conf.d/{{ item }}.conf
    dest: /etc/nginx/conf.d/
  notify: Restart nginx

- name: Install nginx config snippets
  when: nginx_base_snippets | length > 0
  loop: "{{ nginx_base_snippets }}"
  ansible.builtin.copy:
    src: snippets/{{ item }}.conf
    dest: /etc/nginx/snippets/
  notify: Restart nginx

- name: Install ssl-reject-handshake config
  ansible.builtin.include_tasks: ssl_reject_handshake.yml

- name: Generate Diffie-Hellman parameters
  community.crypto.openssl_dhparam:
    path: /etc/ssl/dhparams.pem
    size: "{{ nginx_base_dhparam_size }}"
  notify: Restart nginx

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Ensure nginx is started and enabled
  ansible.builtin.service:
    name: nginx
    enabled: true
    state: started

- name: Include applied role
  when: applied_role_enabled | default(false)
  ansible.builtin.include_role:
    name: mgit_at.roles.applied_role
