---
- name: Install ssl-reject-handshake host
  ansible.builtin.copy:
    src: default-ssl-reject-handshake
    dest: /etc/nginx/sites-available/
  tags: ssl-reject-handshake

- name: Enable ssl-reject-handshake host
  when: nginx_base_ssl_reject_handshake_enabled
  ansible.builtin.file:
    src: /etc/nginx/sites-available/default-ssl-reject-handshake
    dest: /etc/nginx/sites-enabled/default-ssl-reject-handshake
    state: link
  notify: Reload nginx
  tags: ssl-reject-handshake
