---
dependency:
  name: galaxy
  options:
    # https://github.com/ansible/galaxy/issues/2302 - galaxy is sometimes (often?) slow to respond
    timeout: "60"
    # requirements-file: collections.yml
    # ^ This fails?!
driver:
  name: default
# No test on debian by design, this role only runs on Ubuntu
platforms:
  - name: nginxrepo-ubuntu-20.04 # Focal Fossa
    image: ubuntu-20.04
    server_type: cx22
  - name: nginxrepo-ubuntu-22.04 # Jammy Jellyfish
    image: ubuntu-22.04
    server_type: cx22
  - name: nginxrepo-ubuntu-24.04 # Noble Numbat
    image: ubuntu-24.04
    server_type: cx22
provisioner:
  name: ansible
  playbooks:
    create: ../../../../tests/molecule/hcloud_playbooks/create.yml
    destroy: ../../../../tests/molecule/hcloud_playbooks/destroy.yml
verifier:
  name: ansible
