---
- name: Apt upgrade
  ansible.builtin.apt:
    upgrade: dist
  register: upgrade_host_apt_result
  until: upgrade_host_apt_result is not failed
  retries: 60
  delay: 5

- name: Reboot
  ansible.builtin.reboot:
    msg: Ansible updates triggered
    # use something more elaborate than "whoami"
    test_command: systemctl is-system-running
  tags:
    # This will never be idempotent, but it makes no sense to lie about not changing state either
    - molecule-idempotence-notest
- name: Check system state
  ansible.builtin.command: systemctl is-system-running
  # systemctl used deliberately for functionality not in systemd module
  # noqa command-instead-of-module
  register: upgrade_host_running_result
  until: upgrade_host_running_result.rc == 0
  retries: "{{ upgrade_host_system_state_retries }}"
  delay: "{{ upgrade_host_system_state_delay }}"
  changed_when: false # Read-only command
- name: Check service state
  ansible.builtin.command: systemctl --failed
  # systemctl used deliberately for functionality not in systemd module
  # noqa command-instead-of-module
  register: upgrade_host_failed_result
  failed_when: "'failed' in upgrade_host_failed_result.stdout"
  changed_when: false # Read-only command
- name: Include applied role
  when: applied_role_enabled | default(false)
  ansible.builtin.include_role:
    name: mgit_at.roles.applied_role
