---
- name: install docker repo key on debian hosts
  when: ansible_distribution == "Debian"
  ansible.builtin.copy:
    # Source: https://download.docker.com/linux/debian/gpg
    # converted using `gpg --dearmor docker.gpg`
    src: docker_debian.gpg
    dest: /etc/apt/trusted.gpg.d/docker.gpg
  notify: update apt cache

- name: install docker repo key on ubuntu hosts
  when: ansible_distribution == "Ubuntu"
  ansible.builtin.copy:
    # Source: https://download.docker.com/linux/ubuntu/gpg
    # converted using `gpg --dearmor docker.gpg`
    # Debian and Ubuntu keys are identical at the moment by the way, but this might change(?)
    src: docker_ubuntu.gpg
    dest: /etc/apt/trusted.gpg.d/docker.gpg
  notify: update apt cache

- name: add docker apt repo
  ansible.builtin.copy:
    content: |
      deb {{ docker_apt_repo_base_url }} {{ ansible_distribution_release }} stable
    dest: /etc/apt/sources.list.d/docker.list
  notify: update apt cache

- name: Run handlers to update apt cache
  ansible.builtin.meta: flush_handlers
