---
- name: Initialise persistent systemd journal (ubuntu)
  # noqa: no-changed-when - this is already in a handler
  ansible.builtin.command: systemd-tmpfiles --create --prefix /var/log/journal

- name: Initialise persistent systemd journal (debian)
  # noqa: no-changed-when - this is already in a handler
  ansible.builtin.command: setfacl -R -nm g:adm:rx,d:g:adm:rx /var/log/journal

- name: Restart sshd
  ansible.builtin.systemd:
    name: sshd
    state: restarted
  tags:
    - sshd

- name: Restart sshd with systemd reload
  ansible.builtin.systemd:
    name: sshd
    state: restarted
    daemon_reload: true
  tags:
    - sshd

- name: Netplan apply
  # noqa: no-changed-when - this is already in a handler
  ansible.builtin.command: netplan apply

- name: Restart networking
  ansible.builtin.systemd:
    name: networking
    state: restarted
