---
- name: Initialise persistent systemd journal (ubuntu)
  ansible.builtin.command: systemd-tmpfiles --create --prefix /var/log/journal

- name: Initialise persistent systemd journal (debian)
  ansible.builtin.command: setfacl -R -nm g:adm:rx,d:g:adm:rx /var/log/journal

- name: restart sshd
  ansible.builtin.systemd:
    name: sshd
    state: restarted
  tags:
    - sshd

- name: restart sshd with systemd reload
  ansible.builtin.systemd:
    name: sshd
    state: restarted
    daemon_reload: true
  tags:
    - sshd

- name: netplan apply
  ansible.builtin.command: netplan apply

- name: restart networking
  ansible.builtin.systemd:
    name: networking
    state: restarted
