---
nginx_base_pkg_variant: nginx-light
nginx_base_ondrej_repo: false

nginx_base_conf_d_files:
  - connection-upgrade
  - server-tokens
  - hash-bucket-size

nginx_base_snippets:
  - cf-origin-pull
  - tls
  - tls-legacy
  - hsts
  - security-headers
  - proxy-nobuff
  - proxy-forward-headers
  - acmetool

# Only enable on a nginx version later than 1.19.4
nginx_base_ssl_reject_handshake_enabled: false

nginx_base_dhparam_size: 2048
