---
nginx_base_pkg_variant: nginx-light
nginx_base_ondrej_repo: false

nginx_base_conf_d_files:
  - connection-upgrade
  - server_tokens
  - hash_bucket_size

nginx_base_snippets:
  - cf-origin-pull
  - tls
  - tls-legacy
  - hsts
  - security-headers
  - proxy-nobuff
  - proxy-forward-headers
  - acmetool

nginx_base_dhparam_size: 2048
