---
- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    daemon_reload: true

- name: Reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
