---
- name: Converge
  hosts: all
  gather_facts: true
  pre_tasks:
    # Currently we only have a new enough version nginx version in Ubuntu 22.04 setup with nginx-extras
    # from ondrej repo. Bit hacky, but it works.
    - name: Set vars for ssl reject handshake
      when:
        - ansible_distribution == 'Ubuntu'
        - ansible_distribution_major_version | int >= 22
      ansible.builtin.set_fact:
        nginx_base_ssl_reject_handshake_enabled: true
  roles:
    - role: nginx_base
      vars:
        nginx_base_pkg_variant: nginx-extras
        nginx_base_dhparam_size: 1024 # for testing purposes smaller size for speed
