#!/bin/sh

set -eu

GENDIR="$1"
REQUIREDIR="$GENDIR/ethtool-setringmax.service.requires"
SERVICEFILE="/etc/systemd/system/ethtool-setringmax@.service"

mkdir -p "$REQUIREDIR"

intf_l=$(find /sys/class/net -type l -not -lname '*virtual*' -printf '%f\n')
for intf in $intf_l; do
  ln -s "$SERVICEFILE" "$REQUIREDIR/ethtool-setringmax@$intf.service"
done

exit 0
