---
- name: install kubernetes repo key
  copy:
    # Source: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    src: kubernetes.gpg
    dest: /etc/apt/trusted.gpg.d/kubernetes.gpg
  notify: update apt cache

- name: add kubernetes apt repo
  copy:
    content: |
      deb {{ kubernetes_apt_repo_base_url }} kubernetes-xenial main
    dest: /etc/apt/sources.list.d/kubernetes.list
  notify: update apt cache

- name: Run handlers to update apt cache
  meta: flush_handlers
