---
- name: Cleanup apt repo using legacy method
  loop:
    - trusted.gpg.d/kubernetes.gpg
    - sources.list.d/kubernetes.list
  ansible.builtin.files:
    path: "/etc/apt/{{ item }}"
    state: absent
  notify: Update apt cache

- name: Install using deb822_repository
  ansible.builtin.deb822_repository:
    name: "kubernetes{{ kubernetes_version[:4] }}"
    types: deb
    uris:
      # e.g. https://pkgs.k8s.io/core:/stable:/v1.29/deb/
      # Slightly hacky, just use the first 4 letters in the kubernetes_version for now.
      - "{{ apt_repo_kubernetes_repo_base_url }}/core:/stable:/v{{ kubernetes_version[:4] }}/deb/"
    suites:
      - "/"
    # Source: https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key
    signed_by: "{{ apt_repo_kubernetes_repo_gpg_key }}"
  notify: Update apt cache

- name: Run handlers to update apt cache
  ansible.builtin.meta: flush_handlers

- name: Include applied role
  when: applied_role_enabled | default(false)
  ansible.builtin.include_role:
    name: mgit_at.roles.applied_role
