---
- name: Install apt repo using legacy method
  # TODO: clean up legacy method when deb822 version is used
  when:
    # deb822_repository module was added in 2.15
    - ansible_version['major'] == 2
    - ansible_version['minor'] <= 14 or ansible_distribution_major_version | int <= 20
  block:
    - name: Install kubernetes repo key
      ansible.builtin.copy:
        # Source: https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key
        # converted using `gpg --dearmor -o kubernetes.gpg Release.key`
        src: kubernetes.gpg
        dest: /etc/apt/trusted.gpg.d/kubernetes.gpg
      notify: Update apt cache

    - name: Add kubernetes apt repo
      ansible.builtin.copy:
        # e.g. https://pkgs.k8s.io/core:/stable:/v1.29/deb/
        # Slightly hacky, just use the first 4 letters in the kubernetes_version for now.
        content: |
          deb {{ apt_repo_kubernetes_repo_base_url }}/core:/stable:/v{{ kubernetes_version[:4] }}/deb/ /
        dest: /etc/apt/sources.list.d/kubernetes.list
      notify: Update apt cache

- name: Install using deb822_repository
  when:
    - ansible_version['major'] >= 2
    - ansible_version['minor'] >= 15
    # Ubuntu 22.04 and newer for now
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_major_version | int > 20
  ansible.builtin.deb822_repository:
    name: "kubernetes{{ kubernetes_version[:4] }}"
    types: deb
    uris:
    # e.g. https://pkgs.k8s.io/core:/stable:/v1.29/deb/
    # Slightly hacky, just use the first 4 letters in the kubernetes_version for now.
      - "{{ apt_repo_kubernetes_repo_base_url }}/core:/stable:/v{{ kubernetes_version[:4] }}/deb/"
    suites:
      - "/"
    # Source: https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key
    signed_by: "{{ apt_repo_kubernetes_repo_gpg_key }}"
  notify: Update apt cache

- name: Run handlers to update apt cache
  ansible.builtin.meta: flush_handlers

- name: Include applied role
  when: applied_role_enabled | default(false)
  ansible.builtin.include_role:
    name: mgit_at.roles.applied_role
