---
- name: Fail on non Ubuntu distributions
  when: not ansible_distribution == "Ubuntu"
  ansible.builtin.fail:
    msg: "This role only supports Ubuntu"

- name: Install apt repo using legacy method
  # TODO: clean up legacy method when deb822 version is used
  when:
    # deb822_repository module was added in 2.15
    - ansible_version['major'] == 2
    - ansible_version['minor'] <= 14 or ansible_distribution_major_version | int <= 20
  block:
    - name: Install ondrej repo key on host
      ansible.builtin.copy:
        # Source: https://keyserver.ubuntu.com/pks/lookup?fingerprint=on&op=index&search=0x14AA40EC0831756756D7F66C4F4EA0AAE5267A6C
        # converted using `gpg --dearmor nginx.gpg`
        # Unfortunately, this key is only 1024 bits rsa
        src: nginx.gpg
        dest: /etc/apt/trusted.gpg.d/nginx.gpg
      notify: Update apt cache

    - name: Add ondrej apt repo
      ansible.builtin.copy:
        content: |
          deb {{ apt_repo_ubuntu_nginx_repo_base_url }}{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main
        dest: /etc/apt/sources.list.d/nginx.list
      notify: Update apt cache

- name: Install using deb822_repository
  when:
    - ansible_version['major'] >= 2
    - ansible_version['minor'] >= 15
    - ansible_distribution_major_version | int > 20
  ansible.builtin.deb822_repository:
    name: nginx
    types: deb
    uris:
      - "{{ apt_repo_ubuntu_nginx_repo_base_url }}{{ ansible_distribution | lower }}"
    suites:
      - "{{ ansible_distribution_release }}"
    components:
      - main
    # Source: https://keyserver.ubuntu.com/pks/lookup?fingerprint=on&op=index&search=0x14AA40EC0831756756D7F66C4F4EA0AAE5267A6C
    # converted using `gpg --dearmor nginx.gpg`
    # Unfortunately, this key is only 1024 bits rsa
    signed_by: "{{ apt_repo_ubuntu_nginx_repo_gpg_key }}"
  notify: Update apt cache

- name: Set preferences for nginx packages
  ansible.builtin.copy:
    content: |
      Package: *
      Pin: origin "{{ apt_repo_ubuntu_nginx_repo_base_url | regex_replace('^https?://', '') }}"
      Pin-Priority: {{ apt_repo_ubuntu_nginx_repo_priority }}
    dest: /etc/apt/preferences.d/nginx
  notify: Update apt cache

- name: Run handlers to update apt cache
  ansible.builtin.meta: flush_handlers

- name: Include applied role
  when: applied_role_enabled | default(false)
  ansible.builtin.include_role:
    name: mgit_at.roles.applied_role
