---
- name: install ethtool helper (1/2)
  ansible.builtin.file:
    path: "{{ base_systemd_generators_dir }}"
    state: directory

- name: install ethtool helper (2/2)
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items:
    - src: "ethtool-setringmax"
      dest: "/usr/local/lib/"
      mode: "0755"
    - src: "ethtool-setringmax.awk"
      dest: "/usr/local/lib/"
      mode: "0755"
    - src: "ethtool-setringmax.service"
      dest: "/etc/systemd/system/"
      mode: "0644"
    - src: "ethtool-setringmax@.service"
      dest: "/etc/systemd/system/"
      mode: "0644"
    - src: "ethtool-setringmax-generator"
      dest: "{{ base_systemd_generators_dir }}"
      mode: "0755"
  loop_control:
    label: "{{ item.dest }}/{{ item.src }}"

- name: set HW Ring Parameters for existing interfaces
  ansible.builtin.systemd:
    name: ethtool-setringmax.service
    daemon_reload: true
    state: restarted
    enabled: true
  changed_when: false
