---
- name: Clean up previous version of this feature
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ base_systemd_generators_dir }}"
    - /etc/systemd/system/ethtool-setringmax@.service

- name: Install ethtool helper
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items:
    - src: ethtool-setringmax
      dest: /usr/local/lib/
      mode: "0755"
    - src: ethtool-setringmax.awk
      dest: /usr/local/lib/
      mode: "0755"
    - src: ethtool-setringmax.service
      dest: /etc/systemd/system/
      mode: "0644"
  loop_control:
    label: "{{ item.dest }}/{{ item.src }}"
  notify: Restart ethtool-setringmax service

- name: Set HW Ring Parameters for existing interfaces - enable service
  ansible.builtin.systemd:
    name: ethtool-setringmax.service
    enabled: true
    state: started
