---
# see the example_inventory folder for an explanation for group names etc.
- name: roles present on every kubernetes host
  hosts: "{{ hostlist | default('k8s_all') }}"
  roles:
    - role: mgit_at.roles.apt_repo_docker
    - role: mgit_at.roles.apt_repo_helm
    - role: mgit_at.roles.apt_repo_kubernetes
    - role: mgit_at.roles.kubernetes_base
    - role: mgit_at.roles.kubeadm_base
