---
# see the example_inventory folder for an explanation for group names etc.
- name: Roles present on every host
  import_playbook: base.yml
  vars:
    hostlist: k8s_mycluster

- name: Roles present on every kubernetes host
  import_playbook: k8s-base.yml
  vars:
    hostlist: k8s_mycluster

- name: Set up control plane nodes
  hosts: k8s_mycluster_control_plane_nodes
  roles:
    - role: mgit_at.roles.kubeadm_controlplane

- name: Set up other (worker, storage, ingress, egress...) nodes
  hosts:
    - k8s_mycluster_worker_nodes
  roles:
    - role: mgit_at.roles.kubeadm_node

- name: Install flux initially
  hosts: k8s_mycluster_initial_control_plane_node
  roles:
    - role: mgit_at.roles.kubernetes_flux
