---
# Query for latest released version by minor or general:
# https://dl.k8s.io/release/stable-1.23.txt
# https://dl.k8s.io/release/stable.txt

kubernetes_version: 1.33.7
kubernetes_cluster_name: mycluster

# Enter the group names from your hosts.ini file here:
kubernetes_group_name: k8s_mycluster
kubernetes_control_plane_nodes_group_name: k8s_mycluster_control_plane_nodes
kubernetes_initial_control_plane_node_group_name: k8s_mycluster_initial_control_plane_node

kubernetes_encryption_config_keys:
  # generate via `openssl rand -base64 32`
  # For more info, see https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/
  - ThisReallyShouldBeInAVault

kubernetes_max_pods: 123  # default is 110, changed slightly to verify it ends up on nodes

kubernetes_cilium_init_version: 1.33.7  # only the initially installed version, flux takes over afterwards!

# Network settings
kubernetes_api_lb_ip: 1.2.3.4  # externally reachable IP, e.g. from your hosting provider
kubernetes_api_lb_port: 6443

kubernetes_api_cert_sans_extra:
  - "{{ kubernetes_api_lb_ip }}"

kubernetes_network_pod_subnet: 192.168.0.0/17
kubernetes_network_node_cidr_size: 24
kubernetes_network_svc_subnet: 192.168.128.0/20

##### Cluster Addons

# flux

kubernetes_flux_version: 1.2.3  # initial version, will be updated by flux itself
# Generate keypair via `ssh-keygen -t ed25519`
kubernetes_flux_ssh_private_key: ThisReallyShouldBeInAVault
kubernetes_flux_ssh_public_key: ssh-ed25519 base64pubkey
# Get host keys via `ssh-keyscan gitlab.example.com`
kubernetes_flux_ssh_known_hosts: |
  gitlab.example.com ecdsa-sha2-nistp256 base64pubkey
  gitlab.example.com ssh-rsa base64pubkey
  gitlab.example.com ssh-ed25519 base64pubkey
kubernetes_flux_repository_url: ssh://git@gitlab.example.com/group/repository
kubernetes_flux_repository_path: ./clusters/mycluster
# Quick repo link: https://gitlab.example.com/group/repository/-/tree/master/clusters/mycluster
