---
- name: check for supported platform
  ansible.builtin.assert:
    that:
      - ansible_distribution == "Ubuntu"
      - (ansible_distribution_major_version | int) >= 20
    fail_msg: "This must be used on Ubuntu 20.04 or newer"

- name: install containerd
  ansible.builtin.apt:
    name: containerd
    state: present
    force: true

- name: create config directory
  ansible.builtin.file:
    name: /etc/containerd
    state: directory
